"""Render the current cross-repository project status from its JSON source."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any, Mapping

from three_repository_common import require
from three_repository_status import load_project_status


def _mapping(value: Any, *, name: str) -> Mapping[str, Any]:
    require(isinstance(value, dict), f"{name} must be a JSON object")
    return value


def render_project_status(status_path: Path) -> str:
    """Return deterministic Markdown for a validated schema-v2 status record."""

    status = load_project_status(status_path)
    require(
        status["schema_version"] == 2,
        "human-readable project status requires schema version 2",
    )
    empirical = _mapping(status["empirical_status"], name="empirical_status")
    controlled = _mapping(
        empirical["causal4d_controlled"],
        name="causal4d_controlled",
    )
    physical = _mapping(
        empirical["causal4d_confirmatory_physical"],
        name="causal4d_confirmatory_physical",
    )
    calibration = _mapping(
        empirical["independent_execution_calibration"],
        name="independent_execution_calibration",
    )
    prob4d = _mapping(
        empirical["prob4d_to_bayesian_phystwin"],
        name="prob4d_to_bayesian_phystwin",
    )
    controlled_prob4d = _mapping(
        prob4d["controlled_synthetic"],
        name="prob4d controlled_synthetic",
    )
    fresh_prob4d = _mapping(
        prob4d["fresh_real_provider"],
        name="prob4d fresh_real_provider",
    )
    semantic = _mapping(
        empirical["semantic_reweighting"],
        name="semantic_reweighting",
    )
    lines = [
        "# Current cross-repository project status",
        "",
        "<!-- Generated by ci/render_project_status.py from "
        "ci/project_status_v2.json. Do not edit manually. -->",
        "",
        f"- Snapshot: `{status['snapshot_date']}`",
        f"- Claim boundary: `{status['claim_status']}`",
        f"- Next milestone: `{status['primary_next_milestone']}`",
        "",
        "| Area | Status | Evidence boundary |",
        "| --- | --- | --- |",
        (
            "| Causal4D controlled counterfactual | "
            f"`{controlled['status']}` | "
            f"{controlled['registered_gate_count']} registered gates; "
            f"revision `{controlled['evidence_revision']}` |"
        ),
        (
            "| Causal4D confirmatory physical experiment | "
            f"`{physical['status']}` | "
            f"{physical['acquired_executions']}/"
            f"{physical['specified_executions']} acquired; "
            f"{physical['validated_executions']}/"
            f"{physical['specified_executions']} validated; "
            f"`claim_ready={str(physical['claim_ready']).lower()}` |"
        ),
        (
            "| Independent-execution calibration | "
            f"`{calibration['status']}` | "
            "No confirmatory calibration claim until the registered gate passes |"
        ),
        (
            "| Prob4D → Bayesian-PhysTwin, controlled synthetic | "
            f"`{controlled_prob4d['status']}` | "
            f"Report `{controlled_prob4d['report_id']}`; retained revision "
            f"`{controlled_prob4d['evidence_revision']}`; controlled evidence only |"
        ),
        (
            "| Prob4D → Bayesian-PhysTwin, fresh real provider | "
            f"`{fresh_prob4d['status']}` | "
            f"Confirmatory use `{prob4d['confirmatory_physical_use']}` |"
        ),
        (
            "| Semantic reweighting | "
            f"`{semantic['status']}` | Not part of the primary method |"
        ),
        "",
        "## Explicit non-claims",
        "",
    ]
    lines.extend(f"- {value}" for value in status["non_claims"])
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--status",
        type=Path,
        default=Path("ci/project_status_v2.json"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("docs/current_project_status.md"),
    )
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    rendered = render_project_status(arguments.status.resolve())
    output = arguments.output.resolve()
    if arguments.check:
        require(output.is_file(), f"rendered project status does not exist: {output}")
        require(
            output.read_text(encoding="utf-8") == rendered,
            "rendered project status is stale; run ci/render_project_status.py",
        )
        return
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8")


if __name__ == "__main__":
    main()
